# Generated by Django 5.0 on 2025-11-19 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_time', models.CharField(choices=[('00:00', '12:00 AM - 1:00 AM'), ('01:00', '1:00 AM - 2:00 AM'), ('02:00', '2:00 AM - 3:00 AM'), ('03:00', '3:00 AM - 4:00 AM'), ('04:00', '4:00 AM - 5:00 AM'), ('05:00', '5:00 AM - 6:00 AM'), ('06:00', '6:00 AM - 7:00 AM'), ('07:00', '7:00 AM - 8:00 AM'), ('08:00', '8:00 AM - 9:00 AM'), ('09:00', '9:00 AM - 10:00 AM'), ('10:00', '10:00 AM - 11:00 AM'), ('11:00', '11:00 AM - 12:00 PM'), ('12:00', '12:00 PM - 1:00 PM'), ('13:00', '1:00 PM - 2:00 PM'), ('14:00', '2:00 PM - 3:00 PM'), ('15:00', '3:00 PM - 4:00 PM'), ('16:00', '4:00 PM - 5:00 PM'), ('17:00', '5:00 PM - 6:00 PM'), ('18:00', '6:00 PM - 7:00 PM'), ('19:00', '7:00 PM - 8:00 PM'), ('20:00', '8:00 PM - 9:00 PM'), ('21:00', '9:00 PM - 10:00 PM'), ('22:00', '10:00 PM - 11:00 PM'), ('23:00', '11:00 PM - 12:00 AM')], max_length=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayer_app.prayermember')),
            ],
            options={
                'unique_together': {('member', 'prayer_time')},
            },
        ),
    ]
